local ItemList = {
  Weapons = {
    "AK74";
    "AR15";
    "HK416";
    "Khrissy10R";
    "M4A1";
    "MG42";
    "RAM7";
    "SCARH";
  };

  Melees = {
    "Tomahawk";
  };

  Grenades = {
    "MK2";
  };

  Scopes = {
    "IronSights";
    "Holo";
    "ACOG"; --4x
    "PulsarThermion2";
    "ReapIR";
  };

  Helmets = {
    "6B47";
    "Altyn";
    "FastMT";
    "M100";
    "M88";
  };

  Visors = {
    -- Altyn
    "Altyn Face Visor";
    "Altyn Full Visor";

    -- FastMT
    "Ballistic Visor";
    "Fast Visor";
  };

  BodyArmors = {
    "6B45";
    "AVS";
    "IdZ Vest";
    "JPC";
    "LBT6094";
  };

  Backpacks = {
    "Fieldpack 45"
  }
}

return ItemList