local everyItem = {
	weapons = {
		primaryWeapons = {
            "HK416",
            "M4A1",
            "AR15",
            "MG42",
            "SCARH",
            "RAM7",
        },
		secondaryWeapons = {
            "Khrissy10R",
        },
		melees = {
            "Tomahawk"
        },
		throwables = {
            grenades = {
                "Grenade", -- Add Flashbangs/Throwing Axes
            },
        },
	},

	ammos = {},

	mags = {},
}

everyItem.throwables = {}
everyItem.melees = {}

everyItem.consumables = {}

return everyItem
