local weaponCategories = {}

weaponCategories.primaryCategories = {
	"Assault Rifles",
	"Battle Rifles",
	"Carbines",
	"Launchers",
	"Light Machine Guns",
	"Marksman Rifles",
	"Shotguns",
	"Sniper Rifles",
	"Submachine Guns",
}

weaponCategories.secondaryCategories = {
	"Machine Pistols",
	"Pistols",
	"Revolvers",
}

weaponCategories.danebisCategories = {
	"Knifes",
	"Melee",
	"Sabers",
	"Swords",
}

weaponCategories.throwableCategories = {
	"Flashbangs",
	"Grenades",
	"Throwing Melee",
}

weaponCategories.clothesCategories = {
	"WorkingPants",
	"WorkingTShirt",
}

return weaponCategories