local ScopeConfigs = {
    IronSights = {
        aimFOV = 70,
        aimPart2FOV = 65,
        aimSwayAMT = 0.5,
        aimSmooth = 0.00025,
        zoomLevel = 1,
    },

    Holo = {
        aimFOV = 45,
        aimPart2FOV = 40,
        aimSwayAMT = 0.35,
        aimSmooth = 0.0002,
        zoomLevel = 1.8,
    },

    ACOG = {
        aimFOV = 30,
        aimPart2FOV = 20, 
        aimSwayAMT = 0.3,
        aimSmooth = 0.00015,
        zoomLevel = 4,
    },

    PulsarThermion2 = {
        aimFOV = 18,
        aimPart2FOV = 12,
        aimSwayAMT = 0.15,
        aimSmooth = 0.06,
        zoomLevel = 5,
    },
}

return ScopeConfigs